name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v3
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'khanshifaul'
        reponame: 'NRKF_Digital_School'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged